# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7ddca9f5f3b0c877eb37dc2c66b5289d8a7e6d27a01501091a439ab8070113dda7e01907ef3cd967b27c10bb68181bdea3f0d27e169604eb228b7b9ac1b915bf

test:
  secret_key_base: f11242fdf74a8975640ca11724f84d9c963867e03deb4e951476cce30b5aff4b7ea4f0ed2d7e856eea8600ddfdb5269e4a4475dc1f4f9a3b33a9795ac3a1d44d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
